/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LINE_OUT_aliases.h"
#include "LINE_OUT.h"
#include "WaveDAC8_2.h"
#include "WaveDAC8_3.h"
#include "WaveDAC8_1.h"
#include "LINE_IN_aliases.h"
#include "LINE_IN.h"
#include "WaveDAC8_4.h"
#include "WaveDAC8_2_DacClk.h"
#include "WaveDAC8_2_Wave1_DMA_dma.h"
#include "WaveDAC8_2_Wave2_DMA_dma.h"
#include "WaveDAC8_2_VDAC8.h"
#include "WaveDAC8_3_DacClk.h"
#include "WaveDAC8_3_Wave1_DMA_dma.h"
#include "WaveDAC8_3_Wave2_DMA_dma.h"
#include "WaveDAC8_3_VDAC8.h"
#include "WaveDAC8_1_DacClk.h"
#include "WaveDAC8_1_Wave1_DMA_dma.h"
#include "WaveDAC8_1_Wave2_DMA_dma.h"
#include "WaveDAC8_1_VDAC8.h"
#include "WaveDAC8_4_DacClk.h"
#include "WaveDAC8_4_Wave1_DMA_dma.h"
#include "WaveDAC8_4_Wave2_DMA_dma.h"
#include "WaveDAC8_4_VDAC8.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

